### ISSUE TITLE
Which is exe version for?

### ISSUE THREAD

**Issue by Roker2** [gaycoderprincess/TiRTweaks#3]
Hello!

Amazing job! I also tried to fix the game. I am so happy to see, that somebody did more than me.

So, I know two versions of exe:
1. probably 1.0
2. 1.3

**Comment by gaycoderprincess** [comment]
As written in the installation guide:
- Make sure you have the Nestle Edition v1.3 of the game, as this is the only version this plugin is compatible with. (exe size of 1366016 bytes)
